In [15]:
import os

os.getcwd()

'C:\\Users\\NIPUN.S\\Desktop'

In [3]:
os.chdir('C:\\Users\\NIPUN.S\\Desktop')

In [4]:
PATH = os.getcwd()
print(PATH)

C:\Users\NIPUN.S\Desktop


In [5]:
data_path = PATH + '/data'
data_dir_list = os.listdir(data_path)

In [6]:
print(data_dir_list)

['Female', 'Male', 'Transgender']


In [7]:
img_rows=224
img_cols=224
num_channel=3
num_epoch=2

img_data_list=[]
classes_names_list=[]

In [8]:
import cv2

for dataset in data_dir_list:
    classes_names_list.append(dataset) 
    print ('Loading images from {} folder\n'.format(dataset)) 
    img_list=os.listdir(data_path+'/'+ dataset)
    for img in img_list:
        input_img=cv2.imread(data_path + '/'+ dataset + '/'+ img )
        input_img_resize=cv2.resize(input_img,(img_rows, img_cols))
        img_data_list.append(input_img_resize)

Loading images from Female folder

Loading images from Male folder

Loading images from Transgender folder



In [9]:
num_classes = len(classes_names_list)

In [10]:
import numpy as np
img_data = np.array(img_data_list)
img_data = img_data.astype('float32')
img_data /= 255

In [11]:
print (img_data.shape)

img_data = img_data.reshape(img_data.shape[0], img_data.shape[1], img_data.shape[2], num_channel)

(150, 224, 224, 3)


In [12]:
num_of_samples = img_data.shape[0]
input_shape = img_data[0].shape

In [13]:
classes = np.ones((num_of_samples,), dtype='int64')
classes[0:50]=0
classes[50:100]=1
classes[100:]=2


In [17]:
from keras.utils import to_categorical

# convert class labels to on-hot encoding
classes = to_categorical(classes, num_classes)

In [18]:
from sklearn.utils import shuffle

x, y = shuffle(img_data, classes, random_state=2)

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

In [20]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D

In [21]:
model = Sequential()

model.add(Conv2D(32, (3, 3), activation='relu', input_shape=input_shape))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.5))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.5))

model.add(Flatten())
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

In [22]:
model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=["accuracy"])

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 222, 222, 32)      896       
                                                                 
 conv2d_1 (Conv2D)           (None, 220, 220, 32)      9248      
                                                                 
 max_pooling2d (MaxPooling2  (None, 110, 110, 32)      0         
 D)                                                              
                                                                 
 dropout (Dropout)           (None, 110, 110, 32)      0         
                                                                 
 conv2d_2 (Conv2D)           (None, 108, 108, 64)      18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 106, 106, 64)      36928     
                                                        

In [26]:
model.layers[1].get_weights()[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [27]:
model.get_config()

{'name': 'sequential',
 'layers': [{'module': 'keras.layers',
   'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 224, 224, 3),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'conv2d_input'},
   'registered_name': None},
  {'module': 'keras.layers',
   'class_name': 'Conv2D',
   'config': {'name': 'conv2d',
    'trainable': True,
    'dtype': 'float32',
    'batch_input_shape': (None, 224, 224, 3),
    'filters': 32,
    'kernel_size': (3, 3),
    'strides': (1, 1),
    'padding': 'valid',
    'data_format': 'channels_last',
    'dilation_rate': (1, 1),
    'groups': 1,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'module': 'keras.initializers',
     'class_name': 'GlorotUniform',
     'config': {'seed': None},
     'registered_name': None},
    'bias_initializer': {'module': 'keras.initializers',
     'class_name': 'Zeros',
     'config': {},
     'registered_name': None},
    'kernel_regularizer': None,

In [28]:
model.layers[0].get_config()

{'name': 'conv2d',
 'trainable': True,
 'dtype': 'float32',
 'batch_input_shape': (None, 224, 224, 3),
 'filters': 32,
 'kernel_size': (3, 3),
 'strides': (1, 1),
 'padding': 'valid',
 'data_format': 'channels_last',
 'dilation_rate': (1, 1),
 'groups': 1,
 'activation': 'relu',
 'use_bias': True,
 'kernel_initializer': {'module': 'keras.initializers',
  'class_name': 'GlorotUniform',
  'config': {'seed': None},
  'registered_name': None},
 'bias_initializer': {'module': 'keras.initializers',
  'class_name': 'Zeros',
  'config': {},
  'registered_name': None},
 'kernel_regularizer': None,
 'bias_regularizer': None,
 'activity_regularizer': None,
 'kernel_constraint': None,
 'bias_constraint': None}

In [29]:
model.layers[0].input_shape

(None, 224, 224, 3)

In [30]:
model.layers[0].output_shape

(None, 222, 222, 32)

In [31]:
model.layers[0].get_weights()

[array([[[[ 1.30819187e-01,  1.22043490e-03, -7.46863037e-02,
            9.64652896e-02,  5.06858677e-02,  9.42830741e-02,
            1.82143748e-02, -3.86717319e-02,  2.76170373e-02,
            1.27847418e-01, -8.99328440e-02,  6.06965572e-02,
           -9.54713002e-02,  5.76431453e-02, -1.20869726e-01,
            6.62304014e-02,  2.63653696e-03,  8.78323019e-02,
            8.35230947e-03,  1.22183457e-01, -1.12507775e-01,
           -4.37350422e-02,  2.69440711e-02,  3.98484766e-02,
           -1.00158662e-01, -3.20490673e-02, -1.21472083e-01,
            1.11380905e-01,  1.23215809e-01,  4.27543819e-02,
            1.28189489e-01, -6.70007020e-02],
          [ 1.33672968e-01, -6.09749332e-02,  1.26069829e-01,
           -9.94340032e-02,  4.88449633e-03,  1.07527941e-01,
            1.07485205e-02,  5.33378422e-02,  1.21159568e-01,
           -1.08382322e-01, -1.30748570e-01,  3.52613032e-02,
           -3.37651521e-02, -3.42539549e-02,  7.18763918e-02,
           -7.27965757e-

In [34]:
print(np.shape(model.layers[0].get_weights()[0]))
print(np.shape(model.layers[0].get_weights()[1]))


(3, 3, 3, 32)
(32,)


In [35]:
model.layers[0].trainable

True

In [36]:
hist = model.fit(X_train, y_train, batch_size=16, epochs=num_epoch, verbose=1, validation_data=(X_test, y_test))

Epoch 1/2
8/8 [==============================] - 104s 7s/step - loss: 4.6745 - accuracy: 0.3667 - val_loss: 1.1070 - val_accuracy: 0.2667
Epoch 2/2
8/8 [==============================] - 27s 3s/step - loss: 1.0851 - accuracy: 0.3667 - val_loss: 1.0996 - val_accuracy: 0.3000


In [37]:
score = model.evaluate(X_test, y_test, batch_size=16)
print('Test Loss:', score[0])
print('Test Accuracy:', score[1])

2/2 [==============================] - 1s 569ms/step - loss: 1.0996 - accuracy: 0.3000
Test Loss: 1.099566102027893
Test Accuracy: 0.30000001192092896


In [38]:
test_image = X_test[0:1]
print (test_image.shape)

(1, 224, 224, 3)


In [40]:
print(model.predict(test_image))
print(y_test[0:1])

1/1 [==============================] - 0s 284ms/step
[[0.32515705 0.33962205 0.33522096]]
[[1. 0. 0.]]


In [41]:
from sklearn.metrics import confusion_matrix

Y_pred = model.predict(X_test)
print(Y_pred)

1/1 [==============================] - 2s 2s/step
[[0.32515705 0.33962208 0.33522096]
 [0.32575732 0.3389225  0.33532017]
 [0.32684988 0.33662334 0.33652678]
 [0.32487446 0.33956906 0.33555648]
 [0.32396433 0.34011862 0.3359171 ]
 [0.32830226 0.33522165 0.33647612]
 [0.32608843 0.33837917 0.3355324 ]
 [0.32512024 0.33929604 0.33558375]
 [0.32410952 0.3395924  0.3362981 ]
 [0.32851028 0.33478174 0.33670795]
 [0.32334495 0.34220192 0.33445305]
 [0.32566318 0.337592   0.33674482]
 [0.32820114 0.33640984 0.33538905]
 [0.32399088 0.3405988  0.33541036]
 [0.32456142 0.34017688 0.33526167]
 [0.3271584  0.33748674 0.3353548 ]
 [0.32787985 0.3359873  0.33613288]
 [0.32551143 0.34032318 0.3341654 ]
 [0.32363418 0.339866   0.33649987]
 [0.32096425 0.34418055 0.33485523]
 [0.3250435  0.33941478 0.33554173]
 [0.31945288 0.35371897 0.32682812]
 [0.3276528  0.33677667 0.33557048]
 [0.32068586 0.3432814  0.33603275]
 [0.32110372 0.34355694 0.3353393 ]
 [0.32937962 0.33416253 0.33645782]
 [0.3257028  0

In [42]:
y_pred = np.argmax(Y_pred, axis=1)
print(y_pred)

[1 1 1 1 1 2 1 1 1 2 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2 1 1 1 1]


In [43]:
print(confusion_matrix(np.argmax(y_test,axis=1), y_pred))

[[ 0 11  1]
 [ 0  7  1]
 [ 0  8  2]]
